on:
    push:
        branches:
            - main
name: Deploy to staging on push
jobs:
    deploy-staging:
        name: 🎉 Deploy to Staging
        runs-on: ubuntu-latest
        steps:
            - name: 🚚 Get latest code
              uses: actions/checkout@v2

            - name: 🚀 Specifying node version
              uses: actions/setup-node@v2

            - name: 🔨 Building project
              run: npm run build

            - name: 📂 Copying files to server
              uses: SamKirkland/FTP-Deploy-Action@4.3.1
              with:
                  server: ${{ secrets.FTP_SERVER }}
                  username: ${{ secrets.FTP_USERNAME }}
                  password: ${{ secrets.FTP_PASSWORD }}
